version: "3"

services:
  viridis:
    image: krisjanisp/viridis:latest
    container_name: viridis
    restart: always
    volumes:
      - ./data:/viridis/data
      - ./.env:/viridis/.env
    port:
      - "7080:8080"